### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ankane** [ankane/blazer#24]
- [ ] keep params when editing dashboard
- [ ] hide mastermind if no user class
- [ ] handle single value on dashboards
- [ ] better navigation
- [ ] add to dashboard from query page
- [ ] better time defaults (4, weeks, 12 weeks, 52 weeks)
- [ ] a way to organize (categories)
- [ ] treat smart column as string for chart generation
- [ ] show error message on server error

Even Later

- [ ] default name for fork
- [ ] dashing integration (or replacement)?
- [ ] auto-refresh dashboards

**Comment by chrisgogreen** [comment]
+ 1 for the download button

**Comment by spdawson** [comment]
How about "smart" handling of columns/attributes that make use of `ActiveRecord::Enum`?

**Comment by anshul** [comment]
Feature request:  A way to do pivot tables.

**Comment by 6thSigma** [comment]
This may be out of the scope of this gem, but the ability to add a moving average line to graphs would be awesome.

**Comment by w0www** [comment]
up!

**Comment by holden** [comment]
+1 for embeddable charts

**Comment by fwolfst** [comment]
Idea: Next to schema (or even query), show erd (https://github.com/amatsuda/erd or https://github.com/voormedia/rails-erd) if respective gem is available. Btw are you okay with "lazy" idea contributions as comments in this thread?

**Comment by pedrocarmona** [comment]
idea use liquid to build the sql queries:
- instead of  `{ smart_variable }`,  `{{ smart_variable }}` which would be inserted in the liquid context
- allows building dynamic sql with cycles.

**Comment by cyruscavalcante** [comment]
smart variable -> chage null by '%' when nathing is selected on select box
ex:
https://blazer.dokkuapp.com/queries/1-smart-variable?occupation_id=
must result all occupations

**Comment by nfedyashev** [comment]
idea:

When a user has lots of pins to display it would be really handy if you can just order records by date of creation and make the corresponding pin stand out when you hover over a certain line in the table below Mapbox area.

Actually, I've tried to implement it myself but from what I found it's not a trivial task and unfortunately I don't have enough time at the moment.

**Comment by voltechs** [comment]
Allow for optional "schema" support. (`"blazer"."audits"`, `"blazer"."checks"`).

Would help "organize" domain-specific schemas as per "best practices" (not using the `public` schema):
https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PUBLIC
https://wiki.postgresql.org/wiki/Database_Schema_Recommendations_for_an_Application

**Comment by voltechs** [comment]
Got another idea 😇

Could we somehow give Blazer a hint that a bar chart should be stacked?

**Comment by voltechs** [comment]
_Not sure if you want ideas here (lazily, as @fwolfst mentioned), or as separate issues. Let us know, I'm happy to break mine out into their own issues._

**Another idea:** Somehow allow for smart variable selections to accept multiple values. One solution might be if a smart variable is "plural", allow for multi-select. So, `occupation_ids` for example, would let you select multiple. Of course, you'd have to make a call for the user on if it should be `and` or `or`. Or you could have that be another select option...

P.S. Are you accepting PRs for this project? I might start tinkering, but I don't want to waste my time if you don't find value in the ideas.

**Comment by aggy-k** [comment]
Idea: Integrate blazer with authorization gems i.e. Pundit or CanCanCan? 
Would love to share Blazer dashboards with non-technical people for read-access only 😇

**Comment by coorasse** [comment]
💡 Use the new "Discussions" feature of Github to discuss new ideas
